use std::env;
use std::fs;
use std::path::PathBuf;

/// Escape a string as a Rust string literal (including surrounding quotes).
fn rust_str_lit(s: &str) -> String {
    format!("{:?}", s)
}

fn main() {
    // Rebuild multiprints whenever secrets change (cache-safe embeds).
    println!("cargo:rerun-if-env-changed=MULTIPRINTS_TURSO_DATABASE_URL");
    println!("cargo:rerun-if-env-changed=MULTIPRINTS_TURSO_AUTH_TOKEN");
    println!("cargo:rerun-if-env-changed=TURSO_DATABASE_URL");
    println!("cargo:rerun-if-env-changed=TURSO_AUTH_TOKEN");

    let url = env::var("MULTIPRINTS_TURSO_DATABASE_URL")
        .or_else(|_| env::var("TURSO_DATABASE_URL"))
        .unwrap_or_default();
    let token = env::var("MULTIPRINTS_TURSO_AUTH_TOKEN")
        .or_else(|_| env::var("TURSO_AUTH_TOKEN"))
        .unwrap_or_default();

    let url = url.trim();
    let token = token.trim();
    let present = !url.is_empty()
        && !token.is_empty()
        && !url.contains("your-database-name")
        && !token.contains("your-turso-auth");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Generated module included by db.rs — always valid Rust even when empty.
    let rs = format!(
        r#"// @generated by build.rs — do not edit
pub const EMBEDDED_TURSO_PRESENT: bool = {present};
pub const EMBEDDED_TURSO_URL: &str = {url};
pub const EMBEDDED_TURSO_TOKEN: &str = {token};
"#,
        present = present,
        url = rust_str_lit(if present { url } else { "" }),
        token = rust_str_lit(if present { token } else { "" }),
    );
    fs::write(out.join("embedded_turso.rs"), rs).expect("write embedded_turso.rs");

    // Also keep plain text copies for debugging CI artifacts (not used at runtime).
    fs::write(
        out.join("embedded_turso_url.txt"),
        if present { url } else { "" },
    )
    .expect("write turso url txt");
    fs::write(
        out.join("embedded_turso_token.txt"),
        if present { token } else { "" },
    )
    .expect("write turso token txt");

    if present {
        println!(
            "cargo:warning=Turso credentials EMBEDDED into binary (url_len={}, token_len={})",
            url.len(),
            token.len()
        );
    } else {
        println!(
            "cargo:warning=Turso credentials NOT embedded — release builds must set TURSO_DATABASE_URL + TURSO_AUTH_TOKEN"
        );
    }

    tauri_build::build()
}
