use std::env;
use std::fs;
use std::path::PathBuf;

fn rust_str_lit(s: &str) -> String {
    format!("{:?}", s)
}

fn main() {
    println!("cargo:rerun-if-env-changed=MULTIPRINTS_API_BASE_URL");
    println!("cargo:rerun-if-env-changed=MULTIPRINTS_API_SECRET");
    println!("cargo:rerun-if-env-changed=API_BASE_URL");
    println!("cargo:rerun-if-env-changed=API_SECRET");
    println!("cargo:rerun-if-changed=../api/.api_secret");

    let mut url = env::var("MULTIPRINTS_API_BASE_URL")
        .or_else(|_| env::var("API_BASE_URL"))
        .unwrap_or_else(|_| "https://multiprints-api.codegoddy.workers.dev".into());
    url = url.trim().trim_end_matches('/').to_string();

    let mut secret = env::var("MULTIPRINTS_API_SECRET")
        .or_else(|_| env::var("API_SECRET"))
        .unwrap_or_default();
    secret = secret.trim().to_string();

    // Local dev convenience: pick up secret generated by wrangler deploy script
    if secret.is_empty() {
        let path = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into()))
            .join("../api/.api_secret");
        if let Ok(s) = fs::read_to_string(&path) {
            secret = s.trim().to_string();
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }

    let present = !url.is_empty() && !secret.is_empty() && secret.len() >= 16;

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let rs = format!(
        r#"// @generated by frontend/build.rs — do not edit
pub const EMBEDDED_API_PRESENT: bool = {present};
pub const EMBEDDED_API_BASE_URL: &str = {url};
pub const EMBEDDED_API_SECRET: &str = {secret};
"#,
        present = present,
        url = rust_str_lit(if present { &url } else { "" }),
        secret = rust_str_lit(if present { &secret } else { "" }),
    );
    fs::write(out.join("embedded_api.rs"), rs).expect("write embedded_api.rs");

    if present {
        println!(
            "cargo:warning=Cloudflare API client EMBEDDED (url_len={}, secret_len={})",
            url.len(),
            secret.len()
        );
    } else {
        println!(
            "cargo:warning=Cloudflare API NOT embedded — multi-PC remote mode disabled (local Tauri DB only)"
        );
    }
}
